version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vm-sports-classes-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-sports_classes}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sports-network

volumes:
  mysql-data:
    driver: local

networks:
  sports-network:
    driver: bridge
